-- Tạo database
CREATE DATABASE testing;
GO

-- Sử dụng database vừa tạo
USE testing;
GO

-- Bảng Lớp
CREATE TABLE Lop (
    MALOP NCHAR(8) PRIMARY KEY,
    TENLOP NVARCHAR(40) UNIQUE NOT NULL,
    CONSTRAINT CK_Lop_MALOP_UPPER CHECK (MALOP = UPPER(MALOP))
);
GO

-- Bảng Môn học
CREATE TABLE Monhoc (
    MAMH NCHAR(5) PRIMARY KEY,
    TENMH NVARCHAR(40) UNIQUE NOT NULL,
    CONSTRAINT CK_Monhoc_MAMH_UPPER CHECK (MAMH = UPPER(MAMH))
);
GO

-- Bảng Sinh viên
CREATE TABLE Sinhvien (
    MASV NCHAR(8) PRIMARY KEY,
    HO NVARCHAR(10),
    TEN NVARCHAR(40),
    NGAYSINH DATE,
    DIACHI NVARCHAR(100),
    MALOP NCHAR(8) FOREIGN KEY REFERENCES Lop(MALOP),
    CONSTRAINT CK_Sinhvien_MALOP_UPPER CHECK (MALOP = UPPER(MALOP))
);
GO

-- Bảng Giáo viên
CREATE TABLE Giaovien (
    MAGV NCHAR(8) PRIMARY KEY,
    HO NVARCHAR(10),
    TEN NVARCHAR(40),
    SODTLL NCHAR(15),
    DIACHI NVARCHAR(50)
);
GO

-- Bảng Giáo viên đăng ký
CREATE TABLE Giaovien_Dangky (
    MAGV        NCHAR(8),
    MALOP       NCHAR(8)   FOREIGN KEY REFERENCES Lop(MALOP),
    MAMH        NCHAR(5),
    TRINHDO     NCHAR(1)   CHECK (TRINHDO IN ('A', 'B', 'C')),
    NGAYTHI     DATETIME   DEFAULT GETDATE(),
    LAN         SMALLINT   CHECK (LAN >= 1 AND LAN <= 2),
    SOCAUTHI    SMALLINT   CHECK (SOCAUTHI >= 10 AND SOCAUTHI <= 100),
    THOIGIAN    SMALLINT   CHECK (THOIGIAN >= 5 AND THOIGIAN <= 60),
    PRIMARY KEY (MALOP, MAMH, LAN),
    CONSTRAINT FK_Giaovien_Dangky_MAGV FOREIGN KEY (MAGV) REFERENCES Giaovien(MAGV) ON DELETE CASCADE,
    CONSTRAINT FK_Giaovien_Dangky_MAMH FOREIGN KEY (MAMH) REFERENCES Monhoc(MAMH) ON DELETE CASCADE,
    CONSTRAINT CK_Giaovien_Dangky_MALOP_UPPER CHECK (MALOP = UPPER(MALOP)),
    CONSTRAINT CK_Giaovien_Dangky_MAMH_UPPER CHECK (MAMH = UPPER(MAMH))
);
GO

-- Bảng Bộ đề
CREATE TABLE Bode (
    MAMH NCHAR(5),
    CAUHOI INT IDENTITY(1, 1) PRIMARY KEY,
    TRINHDO NCHAR(1) CHECK (TRINHDO IN ('A', 'B', 'C')),
    NOIDUNG NVARCHAR(200),
    A NVARCHAR(50),
    B NVARCHAR(50),
    C NVARCHAR(50),
    D NVARCHAR(50),
    DAP_AN NCHAR(1), -- A/B/C/D
    MAGV NCHAR(8),
    CONSTRAINT FK_Bode_MAGV FOREIGN KEY (MAGV) REFERENCES Giaovien(MAGV) ON DELETE CASCADE,
    CONSTRAINT FK_Bode_MAMH FOREIGN KEY (MAMH) REFERENCES Monhoc(MAMH) ON DELETE CASCADE,
    CONSTRAINT CK_Bode_MAMH_UPPER CHECK (MAMH = UPPER(MAMH))
);
GO

-- Bảng Bảng điểm
CREATE TABLE BangDiem (
    MASV NCHAR(8) FOREIGN KEY REFERENCES Sinhvien(MASV),
    MAMH NCHAR(5),
    LAN SMALLINT CHECK (LAN >= 1 AND LAN <= 2),
    NGAYTHI DATE DEFAULT GETDATE(),
    DIEM FLOAT CHECK (DIEM >= 0 AND DIEM <= 10),
    PRIMARY KEY (MASV, MAMH, LAN),
    CONSTRAINT FK_BangDiem_MAMH FOREIGN KEY (MAMH) REFERENCES Monhoc(MAMH) ON DELETE CASCADE,
    CONSTRAINT CK_BangDiem_MAMH_UPPER CHECK (MAMH = UPPER(MAMH))
);
GO 

CREATE TABLE Taikhoan_Giaovien (
    MAGV NVARCHAR(20) NOT NULL PRIMARY KEY, -- mã giáo viên / tên đăng nhập
    MATKHAU VARCHAR(256) NOT NULL            -- mật khẩu đã được băm
);

CREATE TABLE Taikhoan_Sinhvien (
    MASV NVARCHAR(20) NOT NULL PRIMARY KEY,  -- mã sinh viên / tên đăng nhập
    MATKHAU VARCHAR(256) NOT NULL            -- mật khẩu đã được băm
);
