-- Tạo database
CREATE DATABASE testing;
GO

-- Sử dụng database vừa tạo
USE testing;
GO

-- Bảng Lớp
CREATE TABLE Lop (
    MALOP NCHAR(8) PRIMARY KEY,
    TENLOP NVARCHAR(40) UNIQUE NOT NULL,
    CONSTRAINT CK_Lop_MALOP_UPPER CHECK (MALOP = UPPER(MALOP))
);
GO

-- Bảng Môn học
CREATE TABLE Monhoc (
    MAMH NCHAR(5) PRIMARY KEY,
    TENMH NVARCHAR(40) UNIQUE NOT NULL,
    CONSTRAINT CK_Monhoc_MAMH_UPPER CHECK (MAMH = UPPER(MAMH))
);
GO

-- Bảng Sinh viên
CREATE TABLE Sinhvien (
    MASV NCHAR(8) PRIMARY KEY,
    HO NVARCHAR(40),
    TEN NVARCHAR(10),
    NGAYSINH DATE,
    DIACHI NVARCHAR(100),
    MALOP NCHAR(8) FOREIGN KEY REFERENCES Lop(MALOP),
    CONSTRAINT CK_Sinhvien_MALOP_UPPER CHECK (MALOP = UPPER(MALOP))
);
GO

-- Bảng Giáo viên
CREATE TABLE Giaovien (
    MAGV NCHAR(8) PRIMARY KEY,
    HO NVARCHAR(40),
    TEN NVARCHAR(10),
    SODTLL NCHAR(15),
    DIACHI NVARCHAR(50)
);
GO

-- Bảng Giáo viên đăng ký
CREATE TABLE Giaovien_Dangky (
    MAGV        NCHAR(8)   FOREIGN KEY REFERENCES Giaovien(MAGV),
    MALOP       NCHAR(8)   FOREIGN KEY REFERENCES Lop(MALOP),
    MAMH        NCHAR(5)   FOREIGN KEY REFERENCES Monhoc(MAMH),
    TRINHDO     NCHAR(1)   CHECK (TRINHDO IN ('A', 'B', 'C')),
    NGAYTHI     DATETIME   DEFAULT GETDATE(),
    LAN         SMALLINT   CHECK (LAN >= 1 AND LAN <= 2),
    SOCAUTHI    SMALLINT   CHECK (SOCAUTHI >= 10 AND SOCAUTHI <= 100),
    THOIGIAN    SMALLINT   CHECK (THOIGIAN >= 5 AND THOIGIAN <= 60),
    PRIMARY KEY (MALOP, MAMH, LAN),
    CONSTRAINT CK_Giaovien_Dangky_MALOP_UPPER CHECK (MALOP = UPPER(MALOP)),
    CONSTRAINT CK_Giaovien_Dangky_MAMH_UPPER CHECK (MAMH = UPPER(MAMH))
);
GO

-- Bảng Bộ đề
CREATE TABLE Bode (
    MAMH NCHAR(5) FOREIGN KEY REFERENCES Monhoc(MAMH),
    CAUHOI INT IDENTITY(1, 1) PRIMARY KEY,
    TRINHDO NCHAR(1) CHECK (TRINHDO IN ('A', 'B', 'C')),
    NOIDUNG NVARCHAR(200),
    A NVARCHAR(50),
    B NVARCHAR(50),
    C NVARCHAR(50),
    D NVARCHAR(50),
    DAP_AN NCHAR(1), -- A/B/C/D
    MAGV NCHAR(8) FOREIGN KEY REFERENCES Giaovien(MAGV),
    CONSTRAINT CK_Bode_MAMH_UPPER CHECK (MAMH = UPPER(MAMH))
);
GO

-- Bảng Bảng điểm
CREATE TABLE BangDiem (
    MASV NCHAR(8) FOREIGN KEY REFERENCES Sinhvien(MASV),
    MAMH NCHAR(5) FOREIGN KEY REFERENCES Monhoc(MAMH),
    LAN SMALLINT CHECK (LAN >= 1 AND LAN <= 2),
    NGAYTHI DATE DEFAULT GETDATE(),
    DIEM FLOAT CHECK (DIEM >= 0 AND DIEM <= 10),
    PRIMARY KEY (MASV, MAMH, LAN),
    CONSTRAINT CK_BangDiem_MAMH_UPPER CHECK (MAMH = UPPER(MAMH))
);
GO 